server:
  port: 8082
spring:
  application:
    name: bird
  mongodb:
    uri: mongodb://bird-mongodb:27017/birds_db
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Address of the Eureka Server