server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: bird
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27018/birds_db}
  servlet:
    multipart:
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:10MB}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:10MB}

aws:
  s3:
    bucket: ${AWS_S3_BUCKET:birdbook-images}
    region: ${AWS_REGION:us-east-2}
    bird-prefix: ${AWS_S3_BIRD_PREFIX:birds}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true