server:
  port: 8083 # Port for the client application
spring:
  application:
    name: post
  mongodb:
    uri: mongodb://post-mongodb:27017/posts_db
    database: post_db
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

aws:
  s3:
    bucket: ${AWS_S3_BUCKET:birdbook-images}
    region: ${AWS_REGION:us-east-2}
    post-prefix: ${AWS_S3_POST_PREFIX:images}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Address of the Eureka Server