server:
  port: 8083 # Port for the client application
spring:
  application:
    name: post
  mongodb:
    uri: mongodb://localhost:27019/post_db
    database: post_db
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Address of the Eureka Server